solution = "quicproxy.sln"
generate = "$(SolutionDir)\\generate-vcxproj.exe $(SolutionDir)"
ninja = "bin\\ninja\\ninja.exe -f msvc.ninja"
includes =  [
	".",
	"ext/cutils/inc",
	"ext/BearSSL/inc",
	"ext/BearSSL/src",
]
defines = []

[[target]]
vs = "Debug"
platform = "Win32"
ninja = "win32-debug"
default = "win32-debug check-win32-debug"
defines = [
	"WIN32",
	"DEBUG",
]

[[target]]
vs = "Release"
platform = "Win32"
ninja = "win32-release"
default = "win32-release check-win32-release"
defines = [
	"WIN32",
	"NDEBUG",
]

[[target]]
vs = "Debug"
platform = "x64"
ninja = "win64-debug"
default = "win64-debug check-win64-debug"
defines = [
	"WIN32",
	"DEBUG",
]

[[target]]
vs = "Release"
platform = "x64"
ninja = "win64-release"
default = "win64-release check-win64-release"
defines = [
	"WIN32",
	"NDEBUG",
]

[[target]]
vs = "Arm-Release"
ninja = "armv7-release"
default = "armv7-release"
defines = [
	"__linux__",
	"NDEBUG",
]
includes = [
	"bin/libarm/armv7/include",
	"bin/clang/lib/clang/5.0.1/include",
]

[[project]]
name =  "lib - cutils"
file = "ext/cutils.vcxproj"
target = "bin/obj/{TGT}/cutils.lib"
dirs = [
	"ext/cutils/src",
	"ext/cutils/src/rand",
	"ext/cutils/inc/cutils",
]

[[project]]
name =  "lib - quic"
file = "lib/quic/quic.vcxproj"
target = "bin/obj/{TGT}/quic.lib"
dirs = [
	"lib/quic"
]

[[project]]
name =  "test - quic"
file = "lib/quic/quic_test.vcxproj"
target = "bin/{TGT}/test_quic.exe"

[[project]]
name =  "lib - hq"
file = "lib/hq/hq.vcxproj"
target = "bin/obj/{TGT}/hq.lib"
dirs = [
	"lib/hq"
]

[[project]]
name =  "test - qpack"
file = "lib/hq/qpack_test.vcxproj"
target = "bin/{TGT}/test_qpack.exe"

[[project]]
name =  "bin - qproxy-server"
file = "src/server/server.vcxproj"
target = "bin/{TGT}/qproxy-server.exe"
dirs = [
	"src/server"
]

[[project]]
name =  "bin - qproxy-client"
file = "src/client/client.vcxproj"
target = "bin/{TGT}/qproxy-client.exe"
dirs = [
	"src/client"
]

[[project]]
name =  "bin - http-client"
file = "src/http-client/http-client.vcxproj"
target = "bin/{TGT}/http-client.exe"
dirs = [
	"src/http-client"
]

[[project]]
name =  "test - string"
file = "ext/string_test.vcxproj"
target = "bin/{TGT}/test_str.exe"

[[project]]
name =  "test - header"
file = "lib/hq/header_test.vcxproj"
target = "bin/{TGT}/test_header.exe"

[[project]]
name =  "test - buffer"
file = "lib/buffer_test.vcxproj"
target = "bin/{TGT}/test_buffer.exe"

[[project]]
name = "lib - bearssl"
file = "ext/bearssl.vcxproj"
target = "bin/obj/{TGT}/bearssl.lib"
dirs = [
        "ext/BearSSL/inc",
        "ext/BearSSL/src/aead",
        "ext/BearSSL/src/codec",
        "ext/BearSSL/src/ec",
        "ext/BearSSL/src/hash",
        "ext/BearSSL/src/int",
		"ext/BearSSL/src/kdf",
        "ext/BearSSL/src/mac",
        "ext/BearSSL/src/rand",
        "ext/BearSSL/src/rsa",
        "ext/BearSSL/src/ssl",
        "ext/BearSSL/src/symcipher",
        "ext/BearSSL/src/x509",
        "ext/BearSSL/src",
]
